### ISSUE TITLE
Validate :or on map keys

### ISSUE THREAD

**Issue by blindcoding9** [metosin/malli#935] opened 2023-08-22 17:03 UTC
How can I validate that the map has one key or another?

```clojure
(m/validate [:map
               [:or :A :B]]
              {:A "S"})
```

```clojure
(m/validate [:map
               [:or [:A :string] [:B :string]]]
              {:A "S"})
```

Both:

```
=> Execution error (ExceptionInfo) at malli.core/-exception (core.cljc:138).
:malli.core/invalid-schema
```

**Comment by ikitommi** [comment] 2023-09-02 19:01
duplicate of #474

**Closed by ikitommi** 2023-09-02 19:01 UTC
