### ISSUE TITLE
Unexpected entry when chaining calls to malli.util/assoc-in

### ISSUE THREAD

**Issue by ALai57** [metosin/malli#891] opened 2023-04-11 16:46 UTC
Copied from a Slack thread https://clojurians.slack.com/archives/CLDK6MFMK/p1680790963043859

----------------------------------------------------------------
I came across a Malli behavior I didn’t understand and wanted some advice.

When I chain two mu/assoc-in calls, it seems like the resultant schema has a duplicated field (see below, new-field shows up twice). Is this expected behavior? Am I misusing the assoc-in function?

```clojure
  (def Address
    [:map
     [:street string?]
     [:city string?]
     [:zip int?]
     [:lonlat [:tuple double? double?]]])

  (def Address2
    (-> Address
      (mu/assoc-in [:new-field :v1] [:map [:foo :int]])
      (mu/assoc-in [:new-field :v2] [:map [:foo :int]])))

  Address2
  ;; => [:map [:street string?]
  ;;          [:city string?]
  ;;          [:zip int?]
  ;;          [:lonlat [:tuple double? double?]]
  ;;          [:new-field [:map [:v1 [:map [:foo :int]]]]]
  ;;          [:new-field [:map [:v1 [:map [:foo :int]]] 
  ;;                            [:v2 [:map [:foo :int]]]]]]
```

**Comment by opqdonut** [comment] 2024-08-28 09:51
Can't reproduce this. Might've gotten fixed by some of the recent work on `:map` schemas.

**Closed by opqdonut** 2024-08-28 09:51 UTC
