### ISSUE TITLE
Homogeneous map with specific keys.

### ISSUE THREAD

**Issue by kovasap** [metosin/malli#682] opened 2022-04-02 18:45 UTC
I'm looking for a way to encode a homogeneous map that needs specific keys in malli.  For example,

```
{:id 1 :data1 1.0 :data2 1.0 ...}
```

In this example, I want to be able to say "my map has an `[:id int]`, and the rest of the values are `:keyword :double` pairs".

Currently, I see that I could use `:map` and just enforce my specific keys (and keep the map open), but I really want to get validation that the rest of the entries are in fact `:keyword :double` pairs.  `:map-of` doesn't seem to work because then I can *only* specify the `:keyword :double` pairs and not my `[:id :int]`.

Any ideas how I could accomplish this?

**Comment by frenchy64** [comment] 2022-04-10 15:39
Try `[:and [:map [:id int?]] [:map-of :keyword double?]]`. It doesn't seem to generate very rich values though.

[Playground](https://malli.io/?value=%7B%3Aid%201%20%3Adata1%201.2%20%3Adata2%201%7D&schema=%5B%3Aand%20%5B%3Amap%20%5B%3Aid%20int%3F%5D%5D%20%5B%3Amap-of%20%3Akeyword%20double%3F%5D%5D)

**Comment by kovasap** [comment] 2022-04-10 17:40
Ah that makes sense!  That works for me.  The value generation is less important for me than the validation.

**Comment by kovasap** [comment] 2022-04-10 17:45
Actually that doesn't work: [playground](https://malli.io/?value=%7B%20%3Aid%20%229%2F2%2F02%22%2C%0A%20%20%20%20%20%3Aglucose%2080%2C%0A%20%20%20%20%20%3Ahdl%2045%2C%7D%0A&schema=%5B%3Aand%20%5B%3Amap%20%5B%3Aid%20string%3F%5D%5D%20%5B%3Amap-of%20%3Akeyword%20double%3F%5D%5D).  The `:map` keys must also conform to the `:map-of` spec in the `:and` solution.  This works in your example because an int conforms to a double i guess?

**Comment by frenchy64** [comment] 2022-04-10 18:19
Ah yes, probably a cljs thing. Another two options are to broaden the :map-of schemas to include the :map ones (less accurate validation) or to use :fn to manually dissoc the known keys before validating (perhaps worse error messages).

I think in all cases you might want a custom generator anyway.

-------- Original Message --------

**Comment by boxxxie** [comment] 2022-07-24 13:51
I am running into the same problem, but when i use `:map` and `:map-of` together in different ways `:and mu/union :or ...` i am having trouble making sense of the schema.

i feel like the high level concept is closed map unioned with map-of, but in my case there is a lot of conflict (i'm converting a json schema to malli, and json schema is a pretty awful spec)

```clojure
  (m/schema
    (mu/union
      [:map-of keyword? :string]
      [:map {:closed true}
       [:optional {:optional true} [:enum :a :b]]
       [:specified :int]]))
```

i feel that closed map is needed, and if you can see that my map-of is a different type than my closed map.
so, for each map-entry to be valid, test against both/all schemas. json schema supports 3 or more unions for additional properties.
then, there are also required keys in the spec, so things get more tricky to understand.

also, i see in the code union is a merge, i'm not sure this makes sense to me for this concept of a map.

i saw that there is a sibling thread for this topic that would have us doing something like
```
[:map {:closed [:map-of keyword? :string]}
 [:optional {:optional true} [:enum :a :b]]
 [:specified :int]]
```
i think that's probably enough to solve this issue.

the malli.core code is very very hard for me to understand.
i'm also trying to use the malli.generator code, and i would like this feature to work in both validation/generation.
any help would be very well received.

**Comment by boxxxie** [comment] 2022-07-25 13:12
```clojure
[:and
 [:fn (fn [m]
        (->>
          (dissoc m :specified :optional :required)
          (m/validate (m/schema [:map-of keyword? string?]))))]
 [:map
  [:required {:required true} [:enum :a :b]]
  [:optional {:optional true} [:enum :a :b]]
  [:specified :int]]]
```

this is a workaround that i have used, mainly because i have struggled a lot to debug/edit malli.core code

**Comment by ikitommi** [comment] 2023-03-15 08:36
Duplicate of #43

**Closed by ikitommi** 2023-03-15 08:36 UTC
Labels: duplicate, enhancement, clojurescript
