### ISSUE TITLE
Better support for namespaced transformer names

### ISSUE THREAD

**Issue by DerGuteMoritz** [metosin/malli#324] opened 2020-12-30 22:11 UTC
When a transformer's name is a namespaced keyword, it is currently not possible to include the namespace in schema-hinted transformations. For example, in order to add a schema-hint for the following transformer:

```clojure
(def my-transformer
  (mt/transformer {:name :my/kikka}
                  mt/string-transformer))
```

One has to omit the `my` namespace like this:

```clojure
(def my-schema
  [keyword? {:decode/kikka {:enter 'str/lower-case}}])

(m/decode my-schema "KUKKA" my-transformer) ; => :kukka
```

I feel it would be desirable to support namespaced transformer names in this situation, too, to prevent accidental name clashes.

In practice, it is possible to construct a keyword which contains both namespaces:

```clojure
(keyword (name :decode/my/kikka)) ; => :my/kikka
```

But I guess that this only works by accident. At least the [EDN spec](https://github.com/edn-format/edn#symbols) explicitly disallows it. Also, it's incompatible with auto-resolved keywords, so one would have to resort to hacks like:

```clojure
(keyword "encode" (str (symbol ::kikka)))
```

How about something like this instead:

```clojure
(def my-schema
  [keyword? {:decode {:my/kikka {:enter 'str/lower-case}}}])
```

The only drawback I can think of is that it's a little less convenient when merging property maps. Thoughts?

**Comment by ikitommi** [comment] 2021-01-01 13:13
Thanks for the PR. There is already similar method with JSON Schema & Swagger:

```clj
{:json-schema {:type "string"} ;; 1
{:json-schema/type "string"} ;; 2
```

as property merge uses a simple clojure merge, the last submap wins with 1, but using 2, all the unique properties are merged together. This is intented and by design. With transformations, not sure what is mental default for people, the submap approach looks nice, and I would assume many would use that as the default way to define things, causing potential issues later. But, as transformers are chained, this would still work:

```clj
[:map [:x {:decode {:string my-decode} [:string {:decode {:json my-decode}}]]]
```

what is your use case for needing qualified transformer names?

**Comment by nilern** [comment] 2021-01-07 09:48
`:decode/...` always looked suspicious to me. Shouldn't we just completely switch to using the submap?

Of course it is always possible to make do without qualified names, but is it ever truly necessary?

**Comment by ikitommi** [comment] 2021-01-07 10:43
let's not break the current api, at least before 1.0.0.

**Comment by DerGuteMoritz** [comment] 2021-01-26 19:22
> With transformations, not sure what is mental default for people, the submap approach looks nice, and I would assume many would use that as the default way to define things, causing potential issues later.

Yeah, I can see how forgetting to deep-merge the submap could lead to non-obvious bugs. Maybe turning it inside-out would be a better idea? As in:

```clojure 
(def my-schema
  [keyword? {:my/kikka {:decode {:enter 'str/lower-case}}}])
```

That would at least reduce the potential for such errors a bit.

> what is your use case for needing qualified transformer names?

Mainly for code organization purposes. We use various namespaced properties throughout the schema and by convention, the same namespace also hosts the implementation of whatever interprets these properties. Thus when encountering a namespaced decode/encode schema hint (if it were supported), one would be able to look up the transformer implementation it is relevant for.

**Closed** 2022-01-15 09:56 UTC
Labels: enhancement
